sayi1 = int(input("Birinci sayıyı giriniz:"))
sayi2 = int(input("İkinci sayıyı giriniz:"))
print(sayi1,"+",sayi2,"=",sayi1+sayi2)
print(sayi1,"-",sayi2,"=",sayi1-sayi2)
print(sayi1,"x",sayi2,"=",sayi1*sayi2)
print(sayi1,"üssü",sayi2,"=",sayi1**sayi2)
print(sayi1,"/",sayi2,"=",sayi1/sayi2)  #Paydanın sıfır olmadığını varsayalım
print(sayi1,"//",sayi2,"=",sayi1//sayi2) #Kalanlı bölümde bölüm
print(sayi1,"MOD",sayi2,"=",sayi1%sayi2) #Kalanlı bölümde kalan
